# Train parameters 
batch_size: 32
learning_rate: 0.001
num_epochs: 50
# Model parameters
model_name: "TransformerEncoder"
input_dim: 10
model_dim: 64
num_heads: 4
num_layers: 3
num_classes: 3
# Data parameters
norm_dim: [0,1]  
train_data_path: 'data/raw/Data_train.mat'
test_data_path: 'data/raw/Data_test.mat'