# Train parameters 
batch_size: 160
learning_rate: 0.001
num_epochs: 100
# Model parameters
model_name: "GRUClassifier"
input_dim: 4
model_dim: 100
num_layers: 1
num_classes: 4
# Data parameters
norm_dim: [0,1]  
train_data_path: 'data/processed/Data_train_rig_base.pth'
test_data_path: 'data/processed/Data_test_rig_base.pth'